add timeout option to check deployment action

diff --git a/deploy_status/action.yml b/deploy_status/action.yml
--- a/deploy_status/action.yml
+++ b/deploy_status/action.yml
@@ -9,6 +9,15 @@ inputs:
   url:
     description: "Deployment URL"
     required: true
+  timeout:
+    description: "Timeout in seconds"
+    required: false
+    default: "300"
+  interval:
+    description: "Interval between checks in seconds"
+    required: false
+    default: "5"
+
 runs:
   using: "composite"
   steps:
@@ -18,12 +27,24 @@ runs:
         LGREEN="\033[1;32m" # Light Green
         NC='\033[0m'        # No Color
 
-        status_code=$(curl --head --location --connect-timeout 5 --write-out %{http_code} --silent --output /dev/null ${{ inputs.url }})
-        if [[ "$status_code" -ne 200 ]] || [[ "$status_code" -ne 301 ]] ; then
-          echo -e "\n${LRED}The initial deployment for ${{ inputs.url }} is missing, please fix it and than try to sync with new commits!${NC}"
-          exit 1
-        else
-          echo -e "\n${LGREEN}The initial ${{ inputs.url }} deployment is OK.Proceed with the PR sync step!${NC}"
-          exit 0
-        fi
+        URL="${{ inputs.url }}"
+        TIMEOUT=${{ inputs.timeout }}
+        INTERVAL=${{ inputs.interval }}
+        SECONDS_WAITED=0
+        END=$((SECONDS + TIMEOUT))
+
+        while [ $SECONDS -lt $END ]; do
+          status_code=$(curl --head --location --connect-timeout 5 --write-out %{http_code} --silent --output /dev/null "$URL")
+          echo "HTTP Status Code: $status_code"
+          if [ "$status_code" -eq 200 ] || [ "$status_code" -eq 301 ]; then
+            echo -e "\n${LGREEN}The $URL deployment is OK. Status: $status_code. Proceed with the PR sync step!${NC}"
+            exit 0
+          fi
+          echo -e "\n${LRED}Waiting for URL to be available... ($SECONDS_WAITED/$TIMEOUT seconds)${NC}"
+          sleep $INTERVAL
+          SECONDS_WAITED=$((SECONDS_WAITED + INTERVAL))
+        done
+
+        echo -e "\n${LRED}Timed out waiting for URL to be available. The deployment for $URL is missing, please fix it and then try to sync with new commits!${NC}"
+        exit 1
       shell: bash
